project_id     = "mock-interview-444416"
region         = "us-central1"
environment    = "prod"
app_name       = "kids-activities"
domain_name    = "geethashree.kota.today"
storage_class  = "STANDARD"